#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nrpe
Version  : 3.2.1
Release  : 8
URL      : https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz
Source0  : https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz
Source1  : nrpe.tmpfiles
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: nrpe-bin
Requires: nrpe-config
Requires: nrpe-data
Requires: nrpe-license
BuildRequires : pkgconfig(openssl)
BuildRequires : procps-ng
Patch1: 0001-Fixups-for-autoconf-automake-files.patch
Patch2: 0002-Fixup-recursive-make-recipes-and-create-dirs.patch
Patch3: 0003-Create-default-config-for-stateless.patch
Patch4: 0004-Do-not-regenerate-dhparams-unless-necessary.patch

%description
![Nagios!](https://www.nagios.com/wp-content/uploads/2015/05/Nagios-Black-500x124.png)

%package bin
Summary: bin components for the nrpe package.
Group: Binaries
Requires: nrpe-data = %{version}-%{release}
Requires: nrpe-config = %{version}-%{release}
Requires: nrpe-license = %{version}-%{release}

%description bin
bin components for the nrpe package.


%package config
Summary: config components for the nrpe package.
Group: Default

%description config
config components for the nrpe package.


%package data
Summary: data components for the nrpe package.
Group: Data

%description data
data components for the nrpe package.


%package doc
Summary: doc components for the nrpe package.
Group: Documentation

%description doc
doc components for the nrpe package.


%package license
Summary: license components for the nrpe package.
Group: Default

%description license
license components for the nrpe package.


%prep
%setup -q -n nrpe-3.2.1
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536955339
%configure --disable-static --with-init-type=systemd \
--sysconfdir=/usr/share/defaults/nrpe \
--with-piddir=/run/nrpe
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1536955339
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/nrpe
cp LICENSE.md %{buildroot}/usr/share/doc/nrpe/LICENSE.md
cp macros/LICENSE %{buildroot}/usr/share/doc/nrpe/macros_LICENSE
cp macros/LICENSE.md %{buildroot}/usr/share/doc/nrpe/macros_LICENSE.md
%make_install install-config install-init
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/tmpfiles.d/nrpe.conf

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/nrpe-uninstall
/usr/bin/nrpe
/usr/libexec/check_nrpe

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/nrpe.service
/usr/lib/tmpfiles.d/nrpe.conf

%files data
%defattr(-,root,root,-)
/usr/share/defaults/nrpe/nrpe.cfg

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/nrpe/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/nrpe/LICENSE.md
/usr/share/doc/nrpe/macros_LICENSE
/usr/share/doc/nrpe/macros_LICENSE.md
