#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nrpe
Version  : 3.2.1
Release  : 2
URL      : https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz
Source0  : https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: nrpe-bin
Requires: nrpe-config
BuildRequires : openssl-dev
BuildRequires : procps-ng
Patch1: 0001-Fixups-for-autoconf-automake-files.patch

%description
![Nagios!](https://www.nagios.com/wp-content/uploads/2015/05/Nagios-Black-500x124.png)

%package bin
Summary: bin components for the nrpe package.
Group: Binaries
Requires: nrpe-config

%description bin
bin components for the nrpe package.


%package config
Summary: config components for the nrpe package.
Group: Default

%description config
config components for the nrpe package.


%prep
%setup -q -n nrpe-3.2.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1506702716
%configure --disable-static --with-init-type=systemd
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1506702716
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/nrpe-uninstall
/usr/bin/nrpe
/usr/libexec/check_nrpe

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/nrpe.conf
